# Regenerates public/hokkien.js from taibun's bundled ChhoeTaigi data (CC BY-SA 4.0).
# Usage: pip install taibun msgpack && python scripts/hokkien.py
import json, msgpack, pathlib, taibun
data = pathlib.Path(taibun.__file__).parent / 'data'
load = lambda n: msgpack.unpackb((data / f'{n}.msgpack').read_bytes(), raw=False)
prons, words = load('prons'), load('words')
out = {}
for ch, rs in prons.items():
    default = words.get(ch)
    first = [default] if default and default in rs else []
    out[ch] = ' '.join(first + [r for r in rs if r not in first])
pathlib.Path('public/hokkien.js').write_text(
    '// Hokkien (Tâi-lô) readings: traditional character -> space-separated readings, most common first.\n'
    '// Data: ChhoeTaigi dictionaries via taibun (https://github.com/andreihar/taibun), CC BY-SA 4.0.\n'
    '// Generated by scripts/hokkien.py.\n'
    'export const HOKKIEN = ' + json.dumps(out, ensure_ascii=False, separators=(',', ':')) + ';\n')
print(len(out))
